name: custom_top_navigator
description: A flutter package that makes it easy to create your own navigator anywhere in the widget tree.
version: 0.0.4
homepage: https://github.com/govindmaheshwari2/Custom-top-navigator


environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
